### ISSUE TITLE
makegains output for cavity free maps and make_intdif_gains

### ISSUE THREAD

**Issue by jaimedelacruz** [ISP-SST/sstred#1]
The makegains routine has been modified and now the cavityfree flats have a different name convenction: camXXV_cavityfree.flat_8542_+0_cavityfree.gain.fits instead of camXXV_8542_8542_+0_cavityfree.gain.fits.

The make_intdif_gains loads the header information from camXXV_8542_8542_+0_cavityfree.gain.fits and writes it to the time-dependent gains. But those gaintables have been renamed, so the routine cannot find them.

This bug makes it impossible to reduce CRISP data with time-dependent gains and it is a critical bug.

I am not sure if the new name convention is the intended one (it looks like a bug to me to include cavityfree twice in the name) or if the bug is the fact that the new name has not been propagated to make_intdif_gains. I would revert to the old name convention in makegains.

EDIT: The bug also breaks prepmomfbd, even when run with /unpol which does not make use of the time-dependent gains, but of the cavityfree ones. So there is no way to reduce CRISP data with this bug using MOMFBD.

**Comment by mlofdahl** [comment]
This bug was fixed a long time ago.

Please report bugs and feature requests to https://dubshen.astro.su.se/redmine/projects/crispred/issues rather than here.
